language: 
    cpp

compiler:
    - gcc
    - clang

branches:
    only:
        - master
        - devel

before_install:
    - sudo apt-get update -qq

install:
    - sudo apt-get install libboost-all-dev -qq
    - sudo apt-get install cmake -qq

script:
    mkdir build && cd build && cmake ../ && make
